"""Error thrown on authentication failure."""

from exceptions.CansServerException import CansServerException


class CansServerAuthFailed(CansServerException):
    """Error thrown on authentication failure."""

    pass
